#!/bin/sh

if [ ! -d test_bench ]; then
	mkdir test_bench
fi

if [ ! -d test_bench/ref ]; then
	mkdir test_bench/ref
fi

text_lenght=5
number_file_type=5
number_of_type=4
power=10
file_id=0
wordfile=/usr/share/dict/french

file_id=0

rm test_bench/ref/*

for k in `seq 1 $number_of_type`; do
	for j in `seq 1 $number_file_type`; do	
		for i in `seq 1 $text_lenght`; do
			echo -ne `shuf -n1 /usr/share/dict/french`" " >> test_bench/ref/$file_id
		echo -e $i\r
		done
		file_id=$(( $file_id + 1 ))
	done
	text_lenght=$(( text_lenght * $power ))
done
echo
